apiVersion: v1
kind: Service
metadata:
  name: grafana-svc
  labels:
    app  : grafana-svc
    owner: fkathryn
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.99.105
  selector:
    app: grafana
  ports:
    - name      : port-grafana
      protocol  : TCP
      port      : 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
  labels:
    app  : grafana
    owner: fkathryn
spec:
  selector:
    matchLabels:
       app: grafana
  strategy:
    type: Recreate
  template:
    metadata:
      labels: 
        app  : grafana
        owner: fkathryn
    spec:
      containers: 
      - name           : grafana-deployment
        image          : grafana-image
        imagePullPolicy: Never
        ports:
        - containerPort: 3000 