apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-svc
  labels:
    app  : phpmyadmin-svc
    owner: fkathryn
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.99.102
  selector:
    app: phpmyadmin
  ports:
    - name      : port-phpmyadmin
      protocol  : TCP
      port      : 5000
      targetPort: 5000
---      
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
  labels:
    app  : phpmyadmin
    owner: fkathryn
spec:
  selector:
    matchLabels:
       app: phpmyadmin
  strategy:
    type: Recreate
  template:
    metadata:
      labels: 
        app  : phpmyadmin
        owner: fkathryn
    spec:
      containers: 
      - name           : phpmyadmin
        image          : phpmyadmin-image
        imagePullPolicy: Never
        ports:
        - containerPort: 5000